# Generated by Django 6.0.3 on 2026-06-17 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('valor_evento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupos_disponibles', models.IntegerField()),
                ('estado_evento', models.CharField(default='Disponible', max_length=20)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
        migrations.CreateModel(
            name='InscripcionEvento',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('cantidad_personas', models.IntegerField(default=1)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('id_evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'db_table': 'inscripcion_evento',
                'managed': True,
            },
        ),
    ]
