# Generated by Django 6.0.3 on 2026-06-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': True},
        ),
    ]
