# Generated by Django 6.0.3 on 2026-06-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mesa', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(default='Libre', max_length=50)),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
    ]
