# Generated by Django 6.0.3 on 2026-06-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=12)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('estado', models.CharField(default='Disponible', max_length=20)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
    ]
