# Generated by Django 6.0.3 on 2026-06-18 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamenu',
            options={'managed': False},
        ),
    ]
