# Generated by Django 6.0.3 on 2026-06-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_categoriamenu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamenu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': True},
        ),
    ]
