# Generated by Django 6.0.3 on 2026-06-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(db_column='id_reserva', primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(db_column='nombre_cliente', max_length=100)),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora', models.TimeField(db_column='hora')),
                ('n_personas', models.IntegerField(db_column='n_personas')),
                ('sede', models.CharField(db_column='sede', max_length=50)),
                ('tipo_reserva', models.CharField(choices=[('solo_mesa', 'Solo lugar (Mesa)'), ('mesa_menu', 'Mesa con Menú')], db_column='tipo_reserva', default='solo_mesa', max_length=20)),
                ('monto_pago', models.DecimalField(db_column='monto_pago', decimal_places=2, default=0.0, max_digits=10)),
                ('pago_confirmado', models.BooleanField(db_column='pago_confirmado', default=False)),
                ('platos_seleccionados', models.TextField(blank=True, db_column='platos_seleccionados', null=True)),
                ('estado', models.CharField(db_column='estado', default='Pendiente', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('id_cliente', models.IntegerField(blank=True, db_column='id_cliente', null=True)),
                ('id_empleado', models.IntegerField(blank=True, db_column='id_empleado', null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
    ]
